# -*- coding: utf-8 -*-
"""DRM group 74.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxFVtcB7whqxA_Nufz67BK7ZqC_gWxCz
"""

!pip install yfinance

import yfinance as yf
import pandas as pd

# Define ticker symbol and date range
ticker = 'INDUSINDBK.NS'
start_date = '2024-04-02'
end_date = '2025-03-26'

# Download daily historical data
data = yf.download(ticker, start=start_date, end=end_date, interval='1d')

# Display the first few rows
print(data.head())

# Save to CSV (optional)
data.to_csv('INDUSINDBANK_daily_data.csv')

from google.colab import files
files.download('INDUSINDBANK_daily_data.csv')

import yfinance as yf
import pandas as pd
from google.colab import files

# Define ticker and date range
ticker = 'INDUSINDBK.NS'
start_date = '2024-04-02'
end_date = '2025-03-26'

# Download weekly historical data
weekly_data = yf.download(ticker, start=start_date, end=end_date, interval='1wk')

# Save as CSV
file_name = 'INDUSINDBANK_weekly_data.csv'
weekly_data.to_csv('INDUSINDBANK_weekly_data.csv')

# Download the file to your local system
files.download('INDUSINDBANK_weekly_data.csv')

import yfinance as yf
import pandas as pd
from google.colab import files

# Define ticker and date range
ticker = 'PFC.NS'
start_date = '2024-04-02'
end_date = '2025-03-26'

# Download weekly historical data
weekly_data = yf.download(ticker, start=start_date, end=end_date, interval='1wk')

# Save as CSV
file_name = 'PFC_weekly_data.csv'
weekly_data.to_csv('PFC_weekly_data.csv')

# Download the file to your local system
files.download('PFC_weekly_data.csv')

import yfinance as yf
import pandas as pd
from google.colab import files

# Define ticker and date range
ticker = 'INDUSINDBK.NS'
start_date = '2024-04-01'
end_date = '2025-03-26'

# Download monthly historical data
monthly_data = yf.download(ticker, start=start_date, end=end_date, interval='1mo')

# Save as CSV
file_name = 'INDUSINDBANK_monthly_data.csv'
monthly_data.to_csv('INDUSINDBANK_monthly_data.csv')

# Download the file to your local system
files.download('INDUSINDBANK_monthly_data.csv')

import yfinance as yf
import pandas as pd
from google.colab import files

# Define ticker and date range
ticker = 'PFC.NS'
start_date = '2024-04-01'
end_date = '2025-03-26'

# Download monthly historical data
monthly_data = yf.download(ticker, start=start_date, end=end_date, interval='1mo')

# Save as CSV
file_name = 'PFC_monthly_data.csv'
monthly_data.to_csv('PFC_monthly_data.csv')

# Download the file to your local system
files.download('PFC_monthly_data.csv')

import yfinance as yf
import pandas as pd

# Define ticker symbol and date range
ticker = 'PFC.NS'
start_date = '2024-04-02'
end_date = '2025-03-26'

# Download daily historical data
data = yf.download(ticker, start=start_date, end=end_date, interval='1d')

# Display the first few rows
print(data.head())

# Save to CSV (optional)
data.to_csv('PFC_daily_data.csv')

from google.colab import files
files.download('PFC_daily_data.csv')